# Generated by Django 5.1.4 on 2025-01-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=35)),
                ('model_type', models.CharField(max_length=30)),
                ('model_cost', models.IntegerField()),
            ],
        ),
    ]
